title: Stack Problems
description: My Personal Stack Problems
author: Galen Gao
github: https://github.com/galengao
about: I am a Database Administrator. Currently doing more in oracle, actually in Mysql , Linux and so on.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/galengao
    - text: XML Feed
      url: /feed.xml
url: "https://galengao.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
